//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:10:24 PM CEST 
//


package com.ote.test.structure;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Role.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Role"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FEATURE_TEAM_LEADER"/&gt;
 *     &lt;enumeration value="PRODUCT_OWNER"/&gt;
 *     &lt;enumeration value="PROXY_PRODUCT_OWNER"/&gt;
 *     &lt;enumeration value="QUALITY_ANALYST"/&gt;
 *     &lt;enumeration value="DEV_OPS"/&gt;
 *     &lt;enumeration value="TECHNICAL_LEADER"/&gt;
 *     &lt;enumeration value="BACKEND_DEVELOPER"/&gt;
 *     &lt;enumeration value="FRONTEND_DEVELOPER"/&gt;
 *     &lt;enumeration value="USER_EXPERIENCE"/&gt;
 *     &lt;enumeration value="SUPPORT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Role")
@XmlEnum
@Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
public enum Role {

    FEATURE_TEAM_LEADER,
    PRODUCT_OWNER,
    PROXY_PRODUCT_OWNER,
    QUALITY_ANALYST,
    DEV_OPS,
    TECHNICAL_LEADER,
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    USER_EXPERIENCE,
    SUPPORT;

    public String value() {
        return name();
    }

    public static Role fromValue(String v) {
        return valueOf(v);
    }

}
