//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:10:24 PM CEST 
//


package com.ote.test.structure;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for Tribe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tribe"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="perimeter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="featureTeam" type="{}FeatureTeam" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tribe", propOrder = {
    "id",
    "perimeter",
    "featureTeam"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
public class Tribe implements ToString2
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    protected long id;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    protected String perimeter;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    protected List<FeatureTeam> featureTeam;

    /**
     * Gets the value of the id property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the perimeter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public String getPerimeter() {
        return perimeter;
    }

    /**
     * Sets the value of the perimeter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public void setPerimeter(String value) {
        this.perimeter = value;
    }

    /**
     * Gets the value of the featureTeam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureTeam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureTeam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureTeam }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public List<FeatureTeam> getFeatureTeam() {
        if (featureTeam == null) {
            featureTeam = new ArrayList<FeatureTeam>();
        }
        return this.featureTeam;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            long theId;
            theId = this.getId();
            strategy.appendField(locator, this, "id", buffer, theId, true);
        }
        {
            String thePerimeter;
            thePerimeter = this.getPerimeter();
            strategy.appendField(locator, this, "perimeter", buffer, thePerimeter, (this.perimeter!= null));
        }
        {
            List<FeatureTeam> theFeatureTeam;
            theFeatureTeam = (((this.featureTeam!= null)&&(!this.featureTeam.isEmpty()))?this.getFeatureTeam():null);
            strategy.appendField(locator, this, "featureTeam", buffer, theFeatureTeam, ((this.featureTeam!= null)&&(!this.featureTeam.isEmpty())));
        }
        return buffer;
    }

}
