//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:10:24 PM CEST 
//


package com.ote.test.structure;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for Tribes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tribes"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tribe" type="{}Tribe" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tribes", propOrder = {
    "tribe"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
public class Tribes implements ToString2
{

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    protected List<Tribe> tribe;

    /**
     * Gets the value of the tribe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tribe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTribe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tribe }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public List<Tribe> getTribe() {
        if (tribe == null) {
            tribe = new ArrayList<Tribe>();
        }
        return this.tribe;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2017-09-10T09:10:24+02:00", comments = "JAXB RI v2.2.11")
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            List<Tribe> theTribe;
            theTribe = (((this.tribe!= null)&&(!this.tribe.isEmpty()))?this.getTribe():null);
            strategy.appendField(locator, this, "tribe", buffer, theTribe, ((this.tribe!= null)&&(!this.tribe.isEmpty())));
        }
        return buffer;
    }

}
